/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
 * Generated on: 05-Jan-2025 14:27:08
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,2,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.1582496408197,                 0,                 0 
  },
  {
                   1,    -1.79203654695,                 1 
  },
  {
     0.5550797854312,                 0,                 0 
  },
  {
                   1,   -1.762644221962,                 1 
  },
  {
     0.2630254719122,                 0,                 0 
  },
  {
                   1,   -1.656079075518,                 1 
  },
  {
    0.04138939175369,                 0,                 0 
  },
  {
                   1,   -1.140276135946,                 1 
  },
  {
     0.1906572073082,                 0,                 0 
  },
  {
                   1,                 1,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,2,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.838431340129,   0.9896200174297 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.83131889999,   0.9630702943343 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.830442232761,   0.9209021962229 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.83253976838,   0.8681232161892 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.9169970155177,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
