/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.1 and Signal Processing Toolbox 24.1.
 * Generated on: 05-Jan-2025 13:51:31
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 29
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2024a\extern\include\tmwtypes.h 
 */
const int BL = 29;
const real64_T B[29] = {
  -0.0004231330003149,-0.001947517491744,-0.005090333905478, -0.01036382429094,
   -0.01710820208553, -0.02353637573751, -0.02640443351284,  -0.0218734515516,
  -0.006609345502131,   0.0206308812884,  0.05791972534842,  0.09989072247524,
     0.1387521150023,   0.1662788746556,   0.1762311137356,   0.1662788746556,
     0.1387521150023,  0.09989072247524,  0.05791972534842,   0.0206308812884,
  -0.006609345502131,  -0.0218734515516, -0.02640443351284, -0.02353637573751,
   -0.01710820208553, -0.01036382429094,-0.005090333905478,-0.001947517491744,
  -0.0004231330003149
};
